### ISSUE TITLE
为什么我无法运行呢？

### ISSUE THREAD

**Issue by lvcode** [MarsCWD/HealthKitDemo#1]
pod install后，仍无法运行：ld: library not found for -lMasonry，需要怎么处理呢？

**Comment by MarsCWD** [comment]
你好，你可以选中项目中的Pods，然后在右侧选中PROJECT中的Pods，再在右侧点击Build Settings，将Architectures中的Build Active Architecture Only中的Debug置为NO，再编译下试试

**Comment by lvcode** [comment]
谢谢您的指导，不知道怎么回事，我朋友就能直接运行。
我直接运行会报错：ld: library not found for -lPods-MyHealthModule-Masonry，然后pod install 又报：ld: library not found for -lMasonry。按您说的方法设置为NO也不行。不知道是不是我没有安装好cocoapods

**Comment by MarsCWD** [comment]
cocoapods版本多少，我这边运行环境是0.37.2

**Comment by lvcode** [comment]
cocoapods-0.39.0

**Comment by lvcode** [comment]
cocoapods-0.39.0，是不是高了呢？大神求指教

**Comment by MarsCWD** [comment]
0.39.0这版本在开发中遇到不少问题，所以我们这边团队统一退回到了0.37.2版本了，你可以试试看哈

**Comment by lvcode** [comment]
谢谢大神，我看看百度下怎么回退

**Comment by lvcode** [comment]
如果是自己在“健康”中添加的步数，数据模型中的步数为0，这是个问题么

**Comment by MarsCWD** [comment]
这不是问题哦，业务本就该只从设备中获取步数，数据库中有多个数据来源，需要做数据分离，目前只取了设备中的步数。

**Comment by lvcode** [comment]
可是自己添加数据后，日折线图数据源仍然有该数据，只是步数是0。但是显示所有数据没有这个数据，我表达的不清楚，可惜不能发截图

**Comment by MarsCWD** [comment]
你是指自己添加的数据，在折线图上显示了，但是步数显示的却是0？手机版本号多少

**Comment by lvcode** [comment]
对对对，是这个意思，iOS版本：9.2.1

**Comment by MarsCWD** [comment]
你是在真机上测试的吗？还是模拟器？

**Comment by lvcode** [comment]
真机，用的6。

**Comment by lvcode** [comment]
好奇怪，自己添加的数据，反而从healthKit那儿获取不到步数。

**Comment by MarsCWD** [comment]
这个是正常的，手动添加的数据是不显示的，我倒是奇怪折线图为啥显示了呢。你说的折线图显示是指我那个demo中的折线图吧

**Comment by lvcode** [comment]
嗯，是了，demo中的。一天的折线图

**Comment by MarsCWD** [comment]
我刚也试了下，在健康应用中试着手动添加了下数据，然后在真机上跑了下Demo，发现折线图上多了个点，那个点对应的步数是0，但是右上角显示的今日总步数却是正常的。这是个Bug，不知道你说的是不是和我描述的相符

**Comment by lvcode** [comment]
对的，加几个，就多几个步数为0的数据模型。我是不理解为什么从healthkit获取的手动添加数据是0呢。感觉不是demo的问题，请教下，从哪儿学习healthkit呢？

**Comment by MarsCWD** [comment]
我刚加了断点看了下数据，发现手动添加了数据之后，从数据库取出来的设备步数对应的为0，不知道是不是苹果那边的数据库问题，这个问题我刚修复提交了，你重新下个Demo看下哈，有关HealthKit的学习可以看下我写的这篇文章哈  http://www.jianshu.com/p/ebe14a97525a

**Comment by lvcode** [comment]
谢谢分享，666

**Comment by lvcode** [comment]
我还有个问题 ：最大值：maxLimitCount = self.maxStepCount + self.maxStepCount / 3; 为什么要这么算呢？最小值也是这么算的

**Comment by MarsCWD** [comment]
奥，这个是我们这边的业务需求，要求各个点能够尽量在图表中间排布，这个怎么定无所谓的。
